# Generated by Django 3.0.3 on 2020-02-22 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performpost',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
