# Generated by Django 3.0.3 on 2020-02-26 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenpost',
            name='photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
