# Generated by Django 3.0.3 on 2020-02-22 09:11

from django.db import migrations, models
import first.models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0003_auto_20200221_1546'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(validators=[first.models.validate_text]),
        ),
    ]
