"""
Django settings for drf_practice project.

Generated by 'django-admin startproject' using Django 3.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '&a3$)z**_1ujzqp_6ng%t75@9%2&cfj57gew3@ct09lo9l8zv%'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'first.apps.FirstConfig',
    'filter.apps.FilterConfig',
    'perform.apps.PerformConfig',
    'rest_framework'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'drf_practice.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'drf_practice.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'

# 재정의 하여 사용하는 것이다.
REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
        # 지우면 HTML renderer 는 지원하지 않는다. (format)
    ],

    # 아래의 default paging 옵션을 추가하면 전역에서 적용된다.
    # 정렬을 하지 않은 상태로 사용하면 오류가 뜨는데 models 혹은 views 에서 정렬을 해주면 해결된다.
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 3,  # view 별로 설정 가능하지만 default 지정 한것

    # 현재 프로젝트 내의 모든 뷰에 대해서 호출 횟수가 기본값으로 지정된다.
    # AnonRateThrottle, UserRateThrottle, ScopedRateThrottle 가 있다.
    'DEFAULT_THROTTLE_CLASSES': [
        # 인증된 유저는 user_id, 비인증 유저는 IP별로 횟수 제한
        # 'rest_framework.throttling.UserRateThrottle',  # (전역 세팅) user scope 를 찾으며 값은 아래에 정의되어 있다.
        # 각 APIView 별로 다른 Scope 를 적용하는 경우의 문법이다.
        'rest_framework.throttling.ScopedRateThrottle',  # 전역이 아닌 앱별 세팅을 원하므로 비워두는 것이 맞지만 대체 방법

    ],
    'DEFAULT_THROTTLE_RATES': {
        'user': '10/d',  # 하루 10회 호출 가능 (기본값)
        'custom': '1/d,',  # 하루 1회  호출가능 (뷰 별로 다른 값을 제공하기 위한 커스텀값)
        'custom2': '1/s',  # 초당 1회 (뷰 별로 다른 값을 제공하기 위한 커스텀값)
    },
}
